### ISSUE TITLE
Validation problems because of the incorrect FHIR version

### ISSUE THREAD

**Issue by DanielGitters** [FirelyTeam/firely-terminal-pipeline#16]
**Problem**: When validating in GitHub strange errors are returned because the resources are validated with R4 instead of STU3.

**Fix?**:  Firely terminal should automatically validate with the proper FHIR version -or- a setting parameter should be exposed.

**Comment by alexzautke** [comment]
The issue should be fixed in version [v0.3.3-alpha2](https://github.com/FirelyTeam/firely-terminal-pipeline/releases/tag/v0.3.3-alpha2). Could you give this a try and report back if this works? I’ll create a proper release version afterwards.

Firely Terminal will try to detect the fhirVersion based on the package.json and configure itself automatically.

**Comment by alexzautke** [comment]
Fix confirmed
